export const taskList = [
  {
    id: "a1",
    priority: "Low",
    type: "ToDo",
    title: "Brainstorming",
    context: "Brainstorming brings team member's diverse experience into play",
    comments: 12,
    files: 0,
    avatar: [
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
    ],
    image: "",
  },
  {
    id: "a2",
    priority: "High",
    type: "ToDo",
    title: "Research",
    context: "Brainstorming brings team member's diverse experience into play",
    comments: 10,
    files: 3,
    avatar: ["/kanban/static/avatar.jpg", "/kanban/static/avatar.jpg"],
    image: "",
  },
  {
    id: "a3",
    priority: "High",
    type: "ToDo",
    title: "Wireframes",
    context: "Brainstorming brings team member's diverse experience into play",
    comments: 17,
    files: 2,
    avatar: [
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
    ],
    image: "",
  },
  {
    id: "a4",
    priority: "Low",
    type: "OnProgress",
    title: "Onboarding Illustration",
    context: "",
    comments: 14,
    files: 5,
    avatar: [
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
    ],
    image: "/kanban/static/cupcake.jpg",
  },
  {
    id: "a5",
    priority: "Low",
    type: "OnProgress",
    title: "Moodboard",
    context: "Brainstorming brings team member's diverse experience into play",
    comments: 9,
    files: 10,
    avatar: ["/kanban/static/avatar.jpg"],
    image: "/kanban/static/plant.jpg",
  },
  {
    id: "a6",
    priority: "Low",
    type: "Done",
    title: "Mobile App Design",
    context: "",
    comments: 12,
    files: 0,
    avatar: ["/kanban/static/avatar.jpg", "/kanban/static/avatar.jpg"],
    image: "/kanban/static/app.jpg",
  },
  {
    id: "a7",
    priority: "Low",
    type: "Done",
    title: "Design System",
    context: "Brainstorming brings team member's diverse experience into play",
    comments: 12,
    files: 0,
    avatar: [
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
      "/kanban/static/avatar.jpg",
    ],
    image: "",
  },
];
